# Generated by Django 5.2 on 2025-05-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_iscternship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatura",
            name="cv",
            field=models.FileField(
                blank=True, default="empty.pdf", null=True, upload_to="cv_files"
            ),
        ),
    ]
