# Generated by Django 5.2 on 2025-05-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_iscternship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
