# Generated by Django 5.1.7 on 2025-05-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_iscternship', '0002_candidatura_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='imagem',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagem',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
