# Generated by Django 5.2 on 2025-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_iscternship", "0002_empresa_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="telefone",
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name="empresa",
            name="telefone",
            field=models.CharField(default=None, max_length=12),
        ),
    ]
