# Generated by Django 5.1.7 on 2025-05-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_iscternship', '0003_alter_candidato_imagem_alter_empresa_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cv',
            field=models.FileField(blank=True, default='cv_files/empty.pdf', null=True, upload_to='cv_files'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='cv',
            field=models.FileField(blank=True, default='cv_files/empty.pdf', null=True, upload_to='cv_files'),
        ),
    ]
