# Generated by Django 5.2 on 2025-05-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db_iscternship", "0004_alter_candidato_cv_alter_candidatura_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatura",
            name="feedback_empresa",
            field=models.TextField(blank=True, null=True),
        ),
    ]
