# Generated by Django 5.2 on 2025-05-17 00:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db_iscternship", "0005_alter_candidatura_feedback_empresa"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Report",
        ),
    ]
