# Generated by Django 5.2 on 2025-05-18 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db_iscternship", "0006_delete_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatura",
            name="feedback_empresa",
        ),
    ]
